Create results page
NicolasFujisawa/performance-appraisal-app pull request #18
Opened 2021-09-18 23:06 UTC by leon-lopes

2021-09-18 23:31 UTC, NicolasFujisawa requested changes

2021-09-18 23:31 UTC, NicolasFujisawa commented on front/src/routes.tsx
> +        <Route path="/evaluation" component={Evaluation} />
Pode tirar essa linha, está duplicado

2021-09-18 23:31 UTC, NicolasFujisawa commented on backend/data/migrations.sql
> +insert into evaluation ("start", "end", "isLastEvaluation", "method_id", "teamTeamId") values ('2021-09-17', '2021-10-17', false, 1, 1);
Sou meio contra pois fazemos a avaliação e os scores pela tela

2021-09-19 18:10 UTC, toledompm approved these changes

2021-09-19 18:10 UTC, jasondavindev approved these changes

2021-09-19 18:10 UTC, merged